### ISSUE TITLE
bin_path not taken into account

### ISSUE THREAD

**Issue by maximelebastard** [mcustiel/phiremock-codeception-extension#3]
#Hi,

I made the following configuration in my codeception.yml file:

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - \Codeception\Extension\Phiremock
modules:
    config:
       \Codeception\Extension\Phiremock:
            listen: 0.0.0.0:18080
            debug: true
            startDelay: 1
            bin_path: ../testtesttest/bin
```

But when I run the tests, the process cannot start. I did go to PhiremockProcess.php file, and I discovered that the $path argument from the start method did not change when I change my bin_path into codeception.yml.

Then, I checked the call of the PhiremockProcess::start method, and I found this line in the constructor of Phiremock : 

```
        $this->config['bin_path'] = Config::projectDir() . '../vendor/bin/phiremock';
```

So, where is the bin_path configuration used ?

EDIT : Ok, inheritance. The parent constructor is called later and the config is merged. I get deeper into the code to find why my conf does not work.

**Comment by maximelebastard** [comment]
My bad, I did not respect the format of configuration in codeception.yml.

**Comment by mcustiel** [comment]
No problem, thanks for using phiremock and for reporting :)

**Comment by mcustiel** [comment]
Could you please post here how is the correct configuration for you? Maybe if there are differences with what I put in README I can change it. Thanks.

**Comment by maximelebastard** [comment]
It was what you put in README ;)

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - \Codeception\Extension\Phiremock
    config:
       \Codeception\Extension\Phiremock:
          listen: 0.0.0.0:18080 # defaults to 0.0.0.0:8086
          debug: true
          startDelay: 1
          bin_path: ./bin
```

**Comment by mcustiel** [comment]
Awesome. Thanks!

**Comment by michaelarnauts** [comment]
I have the same issue, but I don't see what I did wrong. I've tried everything from `\Codeception\Extension\Phiremock` or without a leading backslash, or also just specifying `Phiremock`.

When I check the value of `$config` in the `__construct` of `Codeception\Extension\Phiremock`, the config is empty.

```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
    colors: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Phiremock
modules:
    config:
        Yii2:
            configFile: 'config/test/console.php'
            cleanup: false
        REST:
            depends: PhpBrowser
            url: 'http://localhost/index-test.php'
        Phiremock:
            listen: 127.0.0.1:18060
            bin_path: vendor/bin
            debug: true
            startDelay: 5
```
